#not working

# Appveyor doesn't have JDK 8 by default in PATH so we must set it

build_script:
 - cmd: SET tempath=%PATH%
# - cmd: SET PATH="C:\Program Files\Java\jdk1.8.0\bin"
# - cmd: SET PATH=%tempath%
 - git checkout master
 - git config --global credential.helper store
# - ps: Add-Content "$env:USERPROFILE\.git-credentials" "$($env:access_token)`n"
 - git config --global user.email "not-a-real-email@not-a-real-email.not-a-real-email"
 - git config --global user.name "Appveyor Automated Build"
 - cmd: For /f "tokens=2-4 delims=/ " %%a in ('date /t') do (set mydate=%%c-%%a-%%b)
 - cmd: For /f "tokens=1-2 delims=/:" %%a in ('time /t') do (set mytime=%%a%%b)
#
# - cmd: mkdir doc
 - cmd: mkdir %USERPROFILE%\other-place
 - git clone --quiet --branch=master %access_token% %USERPROFILE%\other-place
 - cmd: cd %USERPROFILE%\other-place
 - cmd: SET PATH="C:\Program Files\Java\jdk1.8.0\bin"
 - cmd: javadoc -d doc -classpath "libraries\dragshotMod.jar;libraries\easyogg.jar;libraries\jl1.0.1.jar;libraries\jogg-0.0.7.jar;libraries\jorbis-0.0.15.jar;libraries/NativeBass.jar;libraries/NativeBass-Examples.jar;%CD%" -private -sourcepath "%CD%" BASSLoader.java CarDefine.java CarMaker.java CheckPoints.java ContO.java Control.java GameSparker.java Lobby.java Login.java Mad.java Madness.java Medium.java Mod.java ModInstrument.java ModTrackInfo.java MouseHandler.java Plane.java RadicalBASS.java RadicalMidi.java RadicalMod.java RadicalMp3.java RadicalMusic.java RadicalOgg.java Record.java Smenu.java StageMaker.java SuperClip.java Trackers.java UDPMistro.java UlawUtils.java Utility.java Wheels.java soundClip.java udpOnline.java udpServe.java xtGraphics.java
 - cmd: SET PATH=%tempath%
#
 - cmd: mkdir %USERPROFILE%\gh-pages
#
 - git clone --quiet --branch=gh-pages https://github.com/chrishansen69/OpenNFMM %USERPROFILE%\gh-pages
 #>nul
 - cmd: copy /y %USERPROFILE%\other-place\doc %USERPROFILE%\gh-pages\doc
 - cmd: cd %USERPROFILE%\gh-pages
 - cmd: dir
 - git add -f .
#
# - git add doc/*
 - git commit -m "Generated Javadocs at %mydate%_%mytime% [skip ci]"
 - git push origin gh-pages

#environment:
#  access_token:
# <removed>

skip_commits:
  # Regex for matching commit message
  message: /Generated Javadocs/
  # Commit author's username, name, email or regexp maching one of these.
  author: Appveyor Automated Build

# Note: AppVeyor checkout only the last commit and not the entire branch. So you may have to checkout the wanted branch: git checkout master
on_success: